✨ feat(tools/verify.ts): add verify script
ProjectTwelve/contracts pull request #164
Opened 2022-08-31 22:11 UTC by zh19910202

2022-08-31 23:54 UTC, zh19910202 commented
The deployment information left before cannot pass the validation script. After redeploying, validation works fine. Considering that the new version of the contract has not been enabled in the rinkeby environment, the contract address information of this deployment will be used in the future.

2022-09-02 06:12 UTC, Jerrywang959 approved these changes

2022-09-02 06:12 UTC, Jerrywang959 commented on tools/verify.ts
> +  '/Users/snow/contracts/deployments/rinkeby/WETH9.json',
use relative path instead

2022-09-02 06:12 UTC, Jerrywang959 commented on tools/verify.ts
> +      console.log(err);
console.error or exit?

2022-09-02 06:13 UTC, Jerrywang959 requested changes
approved by mistake

2022-09-02 09:45 UTC, Jerrywang959 approved these changes

2022-09-02 09:46 UTC, merged